### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by erdalkaraca** [matthieuriolo/rivetsjs-stdlib#14]
Hi Matthieu,
I would like to use your lib in a EPL (Eclipse Public License) licensed project.
Unfortunately, GPL is no option as it is not compatible with the EPL. Is there a way to dual license your lib? For example using EPL/MIT/Apache/BSD license?

Thanks!

**Comment by matthieuriolo** [comment]
Hi Erdal

This should not be a problem. I decided to use GPL since I expected it the most free and fair. Is there any specific reason why GPL does not work for you? As far as I'm aware the EPL allows to use GPL.


Best Regards
Matthieu Riolo

_________________________________________

www.ocsource.ch				031 535 38 56
Aarmattweg 69				3052 Zollikofen

			

Am 15.08.2016 um 20:13 schrieb Erdal Karaca <notifications@github.com>:

**Comment by erdalkaraca** [comment]
Hi Matthieu,
Unfortunately, EPL and GPL are not compatible:
https://www.eclipse.org/legal/eplfaq.php#GPLCOMPATIBLE

I am not a lawyer, but I always avoid using GPL software in EPL contexts to avoid legal issues.

Would be great if you dual license your library (MIT license is quite common in non Eclipse environments, rivets uses MIT itself) as it contains many formatters I would want to re-use.
Thanks!

**Comment by matthieuriolo** [comment]
I hope this fixes the problem 885b959fd7e66081801371f41354a1d7289f40b9

Have a nice day and happy coding =)
